name: CD

on:
  release:
    types: [ released ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup
      - name: Build lib
        shell: bash
        run: pnpm run build:lib
        env:
          BUILD: production
      - name: Publish package
        shell: bash
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN  }}
