name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup

  test_integration:
    name: Test Integration
    runs-on: ubuntu-latest

    needs: [Setup]

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup
      - name: Run Build
        run: pnpm run build:lib
        env:
          BUILD: production
      - run: pnpm run test:integration
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: playwright/test-results
          retention-days: 30