name: Pull Request

on:
  push:
    branches:
    - !main
  pull_request:
    branches:
    - !main

env:
  CI: true

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup

  test_style:
    name: Lint & Typecheck
    runs-on: ubuntu-latest

    needs: [setup]

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup
      - name: Check Lint
        run: pnpm run test:lint
      - name: Check Types
        run: pnpm run test:types

  test_components:
    name: Test Components
    runs-on: ubuntu-latest

    needs: [setup]

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup
      - run: pnpm run test:components

  test_end_to_end:
    name: Test End to End
    runs-on: ubuntu-latest

    needs: [test_style, test_components]

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Setup environment and dependencies
        uses: ./.github/actions/setup
      - run: pnpm run build:app
      - run: pnpm run test:end-to-end
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: playwright/test-results
          retention-days: 30